CREATE TABLE daily_update_post
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id   BIGINT                                  NOT NULL,
    team_id       BIGINT                                  NOT NULL,
    date          date                                    NOT NULL,
    general_notes OID,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_daily_update_post PRIMARY KEY (id)
);

CREATE TABLE daily_update_ticket_mention
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    daily_update_id BIGINT                                  NOT NULL,
    ticket_id       BIGINT                                  NOT NULL,
    description     OID                                     NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_daily_update_ticket_mention PRIMARY KEY (id)
);

CREATE TABLE employee_global_roles
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id    BIGINT                                  NOT NULL,
    global_role_id BIGINT                                  NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_employee_global_roles PRIMARY KEY (id)
);

CREATE TABLE employee_projects
(
    employee_id BIGINT NOT NULL,
    project_id  BIGINT NOT NULL,
    CONSTRAINT pk_employee_projects PRIMARY KEY (employee_id, project_id)
);

CREATE TABLE employee_team_roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id BIGINT                                  NOT NULL,
    team_id     BIGINT                                  NOT NULL,
    team_role   BIGINT                                  NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_employee_team_roles PRIMARY KEY (id)
);

CREATE TABLE employees
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_employees PRIMARY KEY (id)
);

CREATE TABLE global_roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(50)                             NOT NULL,
    description VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_global_roles PRIMARY KEY (id)
);

CREATE TABLE projects
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_name        VARCHAR(255)                            NOT NULL,
    project_description VARCHAR(1000),
    team_id             BIGINT                                  NOT NULL,
    deleted_at          TIMESTAMP WITHOUT TIME ZONE,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    team_role  VARCHAR(50)                             NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE status
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status      VARCHAR(50)                             NOT NULL,
    description VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_status PRIMARY KEY (id)
);

CREATE TABLE team_join_requests
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id BIGINT                                  NOT NULL,
    team_id     BIGINT                                  NOT NULL,
    status      VARCHAR(50)                             NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_team_join_requests PRIMARY KEY (id)
);

CREATE TABLE teams
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    team_name   VARCHAR(255)                            NOT NULL,
    description VARCHAR(500),
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_teams PRIMARY KEY (id)
);

CREATE TABLE ticket_dependency
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ticket_id            BIGINT                                  NOT NULL,
    depends_on_ticket_id BIGINT                                  NOT NULL,
    resolved             BOOLEAN                                 NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_ticket_dependency PRIMARY KEY (id)
);

CREATE TABLE tickets
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    jira_id          VARCHAR(50)                             NOT NULL,
    title            VARCHAR(500)                            NOT NULL,
    description      OID,
    owner_id         BIGINT                                  NOT NULL,
    status_id        BIGINT                                  NOT NULL,
    project_id       BIGINT                                  NOT NULL,
    parent_ticket_id BIGINT,
    start_date       date,
    end_date         date,
    deleted_at       TIMESTAMP WITHOUT TIME ZONE,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_tickets PRIMARY KEY (id)
);

ALTER TABLE projects
    ADD CONSTRAINT uc_3c17a4199a2ae95c8d57e5086 UNIQUE (project_name);

ALTER TABLE status
    ADD CONSTRAINT uc_7e4ec21795a95db4ba98ddd3e UNIQUE (status);

ALTER TABLE teams
    ADD CONSTRAINT uc_cd0700ec1e6cff5eaa736b48b UNIQUE (team_name);

ALTER TABLE employees
    ADD CONSTRAINT uc_employees_email UNIQUE (email);

ALTER TABLE employees
    ADD CONSTRAINT uc_employees_username UNIQUE (username);

ALTER TABLE global_roles
    ADD CONSTRAINT uc_global_roles_name UNIQUE (name);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_team_role UNIQUE (team_role);

ALTER TABLE tickets
    ADD CONSTRAINT uc_tickets_jira UNIQUE (jira_id);

ALTER TABLE employee_global_roles
    ADD CONSTRAINT uniq_employee_global_role UNIQUE (employee_id, global_role_id);

ALTER TABLE employee_team_roles
    ADD CONSTRAINT uniq_employee_team UNIQUE (employee_id, team_id);

ALTER TABLE daily_update_post
    ADD CONSTRAINT uniq_employee_team_date UNIQUE (employee_id, team_id, date);

ALTER TABLE team_join_requests
    ADD CONSTRAINT uniq_employee_team_request UNIQUE (employee_id, team_id);

CREATE INDEX idx_ticket_dependency ON ticket_dependency (ticket_id, depends_on_ticket_id);

CREATE INDEX idx_ticket_jira_id ON tickets (jira_id);

CREATE INDEX index_employee_username ON employees (username);

ALTER TABLE daily_update_post
    ADD CONSTRAINT FK_DAILY_UPDATE_POST_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE daily_update_post
    ADD CONSTRAINT FK_DAILY_UPDATE_POST_ON_TEAM FOREIGN KEY (team_id) REFERENCES teams (id);

ALTER TABLE daily_update_ticket_mention
    ADD CONSTRAINT FK_DAILY_UPDATE_TICKET_MENTION_ON_DAILY_UPDATE FOREIGN KEY (daily_update_id) REFERENCES daily_update_post (id);

ALTER TABLE daily_update_ticket_mention
    ADD CONSTRAINT FK_DAILY_UPDATE_TICKET_MENTION_ON_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id);

ALTER TABLE employee_global_roles
    ADD CONSTRAINT FK_EMPLOYEE_GLOBAL_ROLES_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE employee_global_roles
    ADD CONSTRAINT FK_EMPLOYEE_GLOBAL_ROLES_ON_GLOBAL_ROLE FOREIGN KEY (global_role_id) REFERENCES global_roles (id);

ALTER TABLE employee_team_roles
    ADD CONSTRAINT FK_EMPLOYEE_TEAM_ROLES_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE employee_team_roles
    ADD CONSTRAINT FK_EMPLOYEE_TEAM_ROLES_ON_TEAM FOREIGN KEY (team_id) REFERENCES teams (id);

ALTER TABLE employee_team_roles
    ADD CONSTRAINT FK_EMPLOYEE_TEAM_ROLES_ON_TEAM_ROLE FOREIGN KEY (team_role) REFERENCES roles (id);

ALTER TABLE projects
    ADD CONSTRAINT FK_PROJECTS_ON_TEAM FOREIGN KEY (team_id) REFERENCES teams (id);

ALTER TABLE team_join_requests
    ADD CONSTRAINT FK_TEAM_JOIN_REQUESTS_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE team_join_requests
    ADD CONSTRAINT FK_TEAM_JOIN_REQUESTS_ON_TEAM FOREIGN KEY (team_id) REFERENCES teams (id);

ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES employees (id);

ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_PARENT_TICKET FOREIGN KEY (parent_ticket_id) REFERENCES tickets (id);

ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_STATUS FOREIGN KEY (status_id) REFERENCES status (id);

ALTER TABLE ticket_dependency
    ADD CONSTRAINT FK_TICKET_DEPENDENCY_ON_DEPENDS_ON_TICKET FOREIGN KEY (depends_on_ticket_id) REFERENCES tickets (id);

ALTER TABLE ticket_dependency
    ADD CONSTRAINT FK_TICKET_DEPENDENCY_ON_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id);

ALTER TABLE employee_projects
    ADD CONSTRAINT fk_emppro_on_employee FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE employee_projects
    ADD CONSTRAINT fk_emppro_on_project FOREIGN KEY (project_id) REFERENCES projects (id);